<div class=''>
	<div class='page-title'>
		<div class='title_left'>
			<h3>About</h3>
		</div>
	</div>

<div class='clearfix'></div>

<div class='row'>
	<!-- More Information -->
	<div class='col-md-6 col-xs-12'>
		<div class='x_panel'>
			<div class='x_title'>
				<h2><i class='fa fa-info-circle'></i> More Information</h2>
				<ul class='nav navbar-right panel_toolbox'>
			  		<li><a class='close-link'><i class='fa fa-times'></i></a></li>
			  		<li><a class='collapse-link'><i class='fa fa-chevron-up'></i></a></li>
				</ul>
				<div class='clearfix'></div>
			</div>
			<div class='x_content'>
				<p> Scalaris Monitor is a visualisation and monitoring tool 
					for the Scalaris network. It is under active development
					and as such some information may be incorrect and some links
					may not work correctly.</p>
				<p> All blockchain information is extracted directly from a 
				    running node, in realtime when the page is refreshed. 
					As such the results displayed may vary from 
					refresh to refresh and may be different from the "same" view
					on a different node at the same time.</p>
				<p> Geo-IP information is cached in the server since it is 
				    not expected to change much.</p>
				<p> Feedback is welcome and encouraged at Discord
					<div class='x_content'>
						<a href='https://discord.gg/ZeUMV2kcaQ' target='_blank'><i class='fab fa-discord fa-4x col-md-2 col-xs-3'></i></a>
					</div>
				</p>
			</div>
		</div>
	</div>
	<!-- End More information -->

	<!-- Used software -->
	<div class='col-md-6 col-xs-12'>
		<div class='x_panel'>
			<div class='x_title'>
				<h2><i class='fab fa-html5'></i> Used software</h2>
				<ul class='nav navbar-right panel_toolbox'>
			  		<li><a class='close-link'><i class='fa fa-times'></i></a></li>
					<li><a class='collapse-link'><i class='fa fa-chevron-up'></i></a></li>
				</ul>
			<div class='clearfix'></div>
			</div>
			<div class='x_content'>
				<h4>Template </h4>
				<ul>
					<li><a href='https://colorlib.com' target='_blank'>Gentelella Theme</a></li>
					<li><a href='https://getbootstrap.com' target='_blank'>Bootstrap</a></li>
					<li><a href='https://fontawesome.com' target='_blank'>Font Awesome</a></li>
					<li><a href='https://www.gosquared.com/' target='_blank'>Flags</a></li>
				</ul>
			  
				<h4>Javascript Libaries </h4>
				<ul>
					<li><a href='https://jquery.com' target='_blank'>jQuery</a></li>
					<li><a href='https://chartjs.org' target='_blank'>Charts.js</a></li>
					<li><a href='https://datatables.net' target='_blank'>dataTables</a></li>
					<li><a href='https://jvectormap.com' target='_blank'>jVectorMap</a></li>
					<li><a href='https://abpetkov.github.io/switchery/' target='_blank'>Switchery</a></li>
					<li><a href='https://github.com/davidstutz/bootstrap-multiselect' target='_blank'>Bootstrap Multiselect</a></li>
				</ul> 
				
				<h4>PHP Libaries </h4>
				<ul>
					<li><a href='mailto:sergio@inservibile.org' target='_blank'>JSON-RPC PHP</a></li>					   
					<li><a href='https://github.com/coinpaprika/coinpaprika-api-php-client' target='_blank'>Coinpaprika API</a></li> 
				</ul> 
				
				<h4>Other</h4>
				<ul>
  					<li><a href='https://letsencrypt.org/' target='_blank'>TLS Certificates</a></li>					 
				</ul> 
			</div>
		</div>
	</div>
	<!-- End used software -->
 	<!-- Donations -->
	<!--div class='col-md-4 col-xs-12'>
		<div class='x_panel'>
			<div class='x_title'>
				<h2><i class='fas fa-cube black'></i> Donations</h2>
				<ul class='nav navbar-right panel_toolbox'>
	  				<li><a class='close-link'><i class='fa fa-times'></i></a></li>
				</ul>
				<div class='clearfix'></div>
			</div>
			<p> If you find the Scalaris Monitor useful please make a donation to 
				<a href='https://explorer.scalaris.info/block/search.dws?q=Bm4tVuT87Ti4gKud9QZZhzBY4fe22QbLvW' target='_blank'> Bm4tVuT87Ti4gKud9QZZhzBY4fe22QbLvW </a>
			</p>
			<img src='assets/images/cpm_donation_qr.png' class='mx-auto d-block'>
		</div>
	</div-->
	<!-- End Donations -->
</div>
<!-- End Row-->

</div>
</div>
<!-- /page content -->

<!-- footer content -->
<?php include('views/footer.phtml') ?>
<!-- /footer content -->

</div>
</div>

<!-- jQuery -->
<script src='assets/js/jquery.min.js'></script>
<!-- Bootstrap -->
<script src='assets/js/bootstrap.min.js'></script>
<!-- Switchery -->
<script src='assets/js/switchery.min.js'></script>

<!-- Custom Theme Scripts -->
<script src='assets/js/custom.min.js'></script>


</body>
</html>
