<div class=''>
	<div class='page-title'>
		<div class='title_left'>
			<h3>DB update</h3>
		</div>
	</div>

<div class='clearfix'></div>

<div class='row'>
	<!-- DB updated -->
	<div class='col-md-6 col-xs-12'>
		<div class='x_panel'>
			<div class='x_title'>
				<h2><i class='fa fa-info-circle'></i> SQLite3 database updated</h2>
				<ul class='nav navbar-right panel_toolbox'>
			  		<li><a class='close-link'><i class='fa fa-times'></i></a></li>
			  		<li><a class='collapse-link'><i class='fa fa-chevron-up'></i></a></li>
				</ul>
				<div class='clearfix'></div>
			</div>
			<div class='x_content'>
				<p> The database has been upgraded from version <?= $content['oldVersion'] ?>
					to version <?= $content['newVersion'] ?> .
				</p>
			</div>
		</div>
	</div>
	<!-- End More information -->

</div>
<!-- End Row-->

</div>
</div>
<!-- /page content -->

<!-- footer content -->
<?php include('views/footer.phtml') ?>
<!-- /footer content -->

</div>
</div>

<!-- jQuery -->
<script src='assets/js/jquery.min.js'></script>
<!-- Bootstrap -->
<script src='assets/js/bootstrap.min.js'></script>
<!-- Switchery -->
<script src='assets/js/switchery.min.js'></script>

<!-- Custom Theme Scripts -->
<script src='assets/js/custom.min.js'></script>


</body>
</html>
