	<!-- Top Info Bar -->
	<div class='panel panel-default'>  
		<div class='panel-body'>
			<div class='row tile_count'>
				<div class='col-md-2 col-sm-4 col-xs-6 tile_stats_count'>
					<span class='count_top'><i class='fa fa-database'></i> TX in Mempool</span>
					<div class='count'><?= number_format($content['node']->mempoolTx) ?></div>
					<span class='count_bottom'><i class='<?= $content['node']->mempoolUsageP['color'] ?>'><i class='fas <?= $content['node']->mempoolUsageP['icon'] ?>'></i> <?= $content['node']->mempoolUsageP['value'] ?>%</i> Usage</span>
				</div>
				<div class='col-md-2 col-sm-4 col-xs-6 tile_stats_count'>
				<span class='count_top'><i class='fas <?= $content['node']->mempoolUsageP['icon'] ?>'></i> Usage</span>
					<div class='count'><?= $content['node']->mempoolUsage ?> MB</div>
					<span class='count_bottom'>of max. <?= $content['node']->maxMempool ?> MB</span>
				</div>
			</div>
		</div>
	</div>
	<!-- Top Info Bar End-->
	<div class='clearfix'></div>
	<?php if(!empty($error) OR !empty($message)){ ?>
	<div class='col-md-3 col-sm-3 col-xs-12'>
		<?php if(!empty($error)){ ?> <div class='alert alert-danger' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
		<?= $error ?> </div><?php }
		 if(!empty($message)){ ?> <div class='alert alert-success' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
		<?= $message ?> </div><?php } ?>
	</div>  
	<?php } ?>
			<!-- Content -->				   
			<div class='row'>
			
			<!-- Peer List -->
			  <div class='col-md-12 col-sm-12 col-xs-12'>
				<div class='x_panel'>
				  <div class='x_title'>
					<h2>Memory Pool <small>Transactions</small></h2>
					<div class='clearfix'></div>
				  </div>
				  <div class='x_content'>
					<table id='txmempool' class='table table-striped table-bordered table-valign'>
					  <thead>
						<tr>
						  <th>ID</th>
						  <th>Time</th>
						  <th>Size (B)</th>
						  <th>Fee</th>
						  <th>Fee rate</th>
						  <!-- <th>Descendants</th> -->
						  <th style='width:7%;'>Explore</th>
						</tr>
					  </thead>
					  <tbody>
						<?php $i = 0;
							  foreach($content['txs'] as $key => $tx){ ?>
									<tr>
										<td style='padding-right:0px;'><?= $key ?></td>
										<td><?= date('Y-m-d H:i:sT', $tx['time']) ?></td>   
										<td><?= $tx['size'] ?></td>
										<td><?= sprintf('%.8F', $tx['fee']) ?></td>
										<td><?= sprintf('%.8F', round((1000/$tx['size'])*$tx['fee'], 8)) ?></td>
										<!-- <td><?= $tx['descendantcount'] ?></td> -->										
										<td> 
											<div class='btn-group pull-left' style='padding:5px 0 3px 7px; margin-bottom:0px'>
												<button type='button' class='btn btn-default btn-xs'>Details</button>
												<button type='button' class='btn btn-default dropdown-toggle btn-xs' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
													<span class='caret'></span>
													<span class='sr-only'>Toggle Dropdown</span>
												</button>
												<ul class='dropdown-menu'>
													<li><a href='https://explorer.scalaris.info/tx/<?= $key ?>' target='_blank'><i class='fa fa-globe fa-lg' style='color:lightblue'></i> Iquidus</a></li>
												</ul>
											</div>										   
										</td>										   
								  </tr> 
						<?php } ?>						
					  </tbody>
					</table>
				  </div>
				  <div class='clearfix'></div>
				</div>
			  </div>
		  </div>
		</div>
	  </div>
	</div>
	<!-- /page content -->

	<!-- footer content -->
	<?php include('views/footer.phtml') ?>
	<!-- /footer content -->

	<!-- jQuery -->
	<script src='assets/js/jquery.min.js'></script>
	<!-- Bootstrap -->
	<script src='assets/js/bootstrap.min.js'></script>
	<!-- Datatables -->
	<script src='assets/js/jquery.dataTables.min.js'></script>
	<script src='assets/js/dataTables.bootstrap.min.js'></script>
	<script src='assets/js/dataTables.buttons.min.js'></script>
	<script src='assets/js/responsive.bootstrap.js'></script>

	<!-- Custom Theme Scripts -->
	<script src='assets/js/custom.min.js'></script>

	<!-- Datatables -->
	<script>
	  $(document).ready(function() {
		
		 $('#txmempool').DataTable( {
			'paging':   false,
			'bInfo': false,
			'order': [],
			'bFilter': false
		} );
		
	  });
	</script>
	<!-- /Datatables -->
  </body>
</html>