		<!-- Top Info Bar -->
		<div class="panel panel-default">  
			<div class="panel-body">
				<div class="row tile_count">
					<div class="col-md-3 col-sm-4 col-xs-6 tile_stats_count">
						<span class="count_top"><i class="fas fa-exchange-alt"></i> ScalarisDX orders</span>
						<div class="count"><?= $content['openOrderCount'] ?> <small>Open</small></div>
						<span class="count_bottom"><?= $content["rolledBackCount"] ?> Rolled back</span>
					</div>
				</div>
			</div>
		</div>
		<!-- Top Info Bar End-->
		<div class="clearfix"></div>
		<div class="row">
			<div class="col-md-3 col-sm-3 col-xs-12">
				<?php if(!empty($error)){ ?> <div class="alert alert-danger" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<?= $error ?> </div><?php }
				if(!empty($message)){ ?> <div class="alert alert-success" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<?= $message ?> </div><?php } ?>
			</div>  
		</div>

		<!-- Content -->				   
		<div class="row">
			<!-- Open orders list -->
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="x_panel">
					<div class="x_title">
						<h2>Orders<small>Currently active in ScalarisDX</small></h2>
						<div class="clearfix"></div>
					</div>
					<div class="x_content">
						<table id="orders" class="table table-striped table-bordered table-valign">
							<thead>
								<tr>
							 		<!--th>ID</th-->
							 		<th>Maker</th>
									<th>Maker Size</th>
									<th>Taker</th>
									<th>Taker Size</th>
									<th>Updated</th>
									<th>Type</th>
									<th>Status</th>
									<th>Details</th>
								</tr>
					  		</thead>
							<tbody>
								<?php if ($content['totalCount'] > 0) {;
							  		foreach($content['order'] as $order){ ?>
									<tr>
										<td><?=$order['maker'] ?></td>
										<td><?=$order['makerSize'] ?></td>
										<td><?=$order['taker'] ?></td>
										<td><?=$order['takerSize'] ?></td>
										<td><?=$order['updatedAt'] ?></td>
										<td><?=$order['orderType'] ?></td>
										<td><?=$order['status'] ?></td>

										<td>										   
											<div class="btn-group pull-right" style="padding:5px 0px 3px 0px; margin-bottom:0px">
												<button type="button" class="btn btn-default btn-xs" data-toggle="modal" <?php echo 'data-target="#order'.$i.'"'; ?>>Details</button>
												<!-- Modal -->
												<div <?php echo 'id="order'.$i.'"'; ?> class="modal fade" role="dialog">
  													<div class="modal-dialog modal-dialog-scrollable modal-lg">
    													<!-- Modal content-->
    													<div class="modal-content">
      														<div class="modal-header">
		   														<button type="button" class="close" data-dismiss="modal">&times;</button>
        														<h4 class="modal-title">NFT details</h4>
      														</div>
      														<div class="modal-body">
																<?php
																	$orderinfo = $content['scalarisd']->dxgetorder($order['id']);
																	foreach($orderinfo as $key => $data){ ?>
																		<p><?= $key . ": " . $data ?></p>
																<?php } ?>
      														</div>
      														<div class="modal-footer">
        														<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      														</div>
    													</div>
  													</div>
												</div>
										<!--		<button type="button" class="btn btn-default dropdown-toggle btn-xs" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
													<span class="caret"></span>
													<span class="sr-only">Toggle Dropdown</span>
												</button>
												<ul class="dropdown-menu">
													<li><a href="?p=nfts&proto=<?= $token['nftProtocolId'] ?>" target="_self">Same protocol</a></li>
													<li><a href="?p=nfts&owner=<?= $token['nftOwnerKeyId'] ?>" target="_self">Same owner</a></li>
													<li><a href="?p=nfts&proto=<?= $token['nftProtocolId'] ?>&owner=<?= $token['nftOwnerKeyId'] ?>" target="_self">Same protocol and owner</a></li>
													<li class="divider"></li>
													<li><a href="https://iquidus-01.crownplatform.com/api/getrawtransaction?txid=<?= $token['registrationTxHash']?>&decrypt=1" target="_blank"> Txn details</a></li>
													<li class="divider"></li>
													<li><a href="https://iquidus-01.crownplatform.com/tx/<?= $token['registrationTxHash'] ?>" target="_blank"><i class="fa fa-globe fa-lg" style="color:lightblue"></i> Iquidus</a></li>
													<li><a href="https://insight-02.crownplatform.com/tx/<?= $token['registrationTxHash'] ?>" target="_blank"><i class="fa fa-globe fa-lg" style="color:lightblue"></i> Insight</a></li>
													<li><a href="https://explorer.scalaris.info/crw/tx.dws?<?= $token['registrationTxHash'] ?>" target="_blank"><i class="fa fa-globe fa-lg" style="color:lightblue"></i> Iquidus</a></li>
												</ul>  -->
											</div>										   
								   		</td>										   


									</tr>
								<?php } } ?>						
							</tbody>
						</table>
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
		<!-- /page content -->
		</div>

		<!-- footer content -->
		<?php include('views/footer.phtml') ?>
		<!-- /footer content -->
		</div>
		</div>

		<!-- jQuery -->
		<script src="assets/js/jquery.min.js"></script>
		<!-- Bootstrap -->
		<script src="assets/js/bootstrap.min.js"></script>
		<!-- Datatables -->
		<script src="assets/js/jquery.dataTables.min.js"></script>
		<script src="assets/js/dataTables.bootstrap.min.js"></script>
		<script src="assets/js/dataTables.buttons.min.js"></script>
		<script src="assets/js/responsive.bootstrap.js"></script>

		<!-- Custom Theme Scripts -->
		<script src="assets/js/custom.min.js"></script>

		<!-- Datatables -->
		<script>
	 		$(document).ready(function() {
			$('#orders').DataTable( {
				"paging": true,
				"lengthChange": true,
				"lengthMenu": [ [10, 25, 50, -1], [10, 25, 50, "All"] ],
				"bInfo": false,
				"order": [[ 4, "desc" ]]
			} );		
	  		});
		</script>
		<!-- /Datatables -->
  	</body>
</html>