		 <!-- Top Info Bar -->
		 <div class="panel panel-default">  
			<div class="panel-body">
				<div class="row tile_count">
					<div class="col-md-3 col-sm-4 col-xs-6 tile_stats_count">
						<span class="count_top"><i class="fas fa-user-friends"></i> Total Peers</span>
						<div class="count"><?= $content['tPeers'] ?></div>
						<span class="count_bottom"><span class="green" ><i class="fa fa-plus"></i><?= $content['nPeers'] ?></span> New Peers</span>
					</div>
					<div class="col-md-3 col-sm-4 col-xs-6 tile_stats_count">
						<span class="count_top"><i class="fa fa-star" style="color:#EDDA74;"></i> Most Popular Client Version</span>
						<div class="count"><?= $content['mpCli'] ?></div>
						<span class="count_bottom"><span style="color:#EDDA74;"> <?= $content['mpCliC'] ?></span> Peers</span>
					</div>
					<div class="col-md-3 col-sm-4 col-xs-6 tile_stats_count">
						<span class="count_top"><i class="fa fa-globe"></i> Most Popular Country</span>
						<div class="count"> <img src="assets/images/flags/32/<?=$content['mpCou']?>.png"/><?= " ".$content['mpCou'] ?>
						</div>
						<span class="count_bottom"><span class="blue" ><?= $content['mpCouC'] ?></span> Peers</span>
					</div>
					<div class="col-md-3 col-sm-4 col-xs-6 tile_stats_count">
						<span class="count_top"><i class="fa fa-server" style="color:orange;"></i> Most Popular ISP</span>
						<div class="count"><?= $content['mpIsp'] ?></div>
						<span class="count_bottom"><span style="color:orange;"><?= $content['mpIspC'] ?></span> Peers</span>
					</div>
					<div class="col-md-3 col-sm-4 col-xs-6 tile_stats_count">
						<span class="count_top"><i class="fa fa-cloud" style="color:lightblue;"></i> Traffic by Current Peers</span>
						<div class="count"><?= ($content['cTraf'] >= 1000) ? round($content['cTraf']/1000,2)." <small>TB</small>" : $content['cTraf']." <small>GB</small>"?></div>
						<span class="count_bottom"><i style="color:lightblue;"> <?= $content['cTrafP'] ?>%</i> of total Traffic</span>
					</div>
				</div>
			</div>
		</div>
		<!-- Top Info Bar End-->
		<div class="clearfix"></div>
		<div class="row">
			<div class="col-md-3 col-sm-3 col-xs-12">
				<?php if(!empty($error)){ ?> <div class="alert alert-danger" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<?= $error ?> </div><?php }
				if(!empty($message)){ ?> <div class="alert alert-success" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<?= $message ?> </div><?php } ?>
			</div>  
		</div>

		<!-- Content -->				   
		<div class="row">
			
		<!-- Peer List -->
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="x_panel">
				<div class="x_title">
					<h2>Peers <small>Connected to this node</small></h2>
					<div class="clearfix"></div>
				</div>
				<div class="x_content">
					<table id="connectedpeers" class="table table-striped table-bordered table-valign">
						<thead>
							<tr>
						  		<th>ID</th>
						  		<th>IP</th>
								<?php if($content['geo']){ ?> <th>Country</th> <?php } ?>
								<th>Services</th>
							  	<th>Ping</th>
								<?php if($content['geo']){ ?> <th>ISP</th> <?php } ?>
						  		<th>Age <span style="font-weight:normal;">(m)</span></th>
						  		<th>Client</th>
						  		<th>Traffic <span style="font-weight:normal;">(MB)</span></th>
							</tr>
						</thead>
						<tbody>
							<?php $i = 0;
								foreach($content['peers'] as $peer){ ?>
								<tr>
									<td style="padding-right:0px;"><?=$peer->id ?></td>
									<td><?=$peer->ip ?></td>  
									<?php if($content['geo']){?><td><?php if(!empty($peer->country)){ ?><img src="assets/images/flags/16/<?=$peer->country ?>.png"/> <?php echo $peer->country; } ?></td><?php } ?>  
									<td style="padding-right:0px;">
										<?php
											if(!empty($peer->services)){
												foreach($peer->services as $key => $service){
													echo '<button type="button" class="btn btn-default btn-xs" data-toggle="tooltip" data-placement="top" title="'.$key.'">'.$service.'</button>';													 
												}	
											} ?>	 
									</td>
									<td> <?= $peer->ping ?></td>
									<?php if($content['geo']){ ?> <td><?php if($peer->hosted){ ?><i class="fa fa-cloud"></i><?php } else{ ?><span style="padding-left:18px;"></span><?php } ?> <?= substr($peer->isp,0,23) ?></td> <?php } ?>  
									<td> <?= $peer->age ?></td>
									<td><?php if($peer->snoopy){ ?><i class="fa fa-binoculars"></i><?php } else{ ?><span style="padding-left:18px;"></span><?php } ?> <?= substr($peer->client,0,20) ?></td>  
									<td> <?= $peer->traffic ?></td>
								</tr>  
							<?php } ?>						
					  	</tbody>
					</table>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	</div>
	</div>
	</div>
	<!-- /page content -->

	<!-- footer content -->
	<?php include('views/footer.phtml') ?>
	<!-- /footer content -->

	<!-- jQuery -->
	<script src="assets/js/jquery.min.js"></script>
	<!-- Bootstrap -->
	<script src="assets/js/bootstrap.min.js"></script>
	<!-- Datatables -->
	<script src="assets/js/jquery.dataTables.min.js"></script>
	<script src="assets/js/dataTables.bootstrap.min.js"></script>
	<script src="assets/js/dataTables.buttons.min.js"></script>
	<script src="assets/js/responsive.bootstrap.js"></script>

	<!-- Custom Theme Scripts -->
	<script src="assets/js/custom.min.js"></script>

	<!-- Datatables -->
	<script>
	  $(document).ready(function() {
		
		$('#connectedpeers').DataTable( {
			"paging": true,
			"bInfo": false,
			"order": [[ 8, "desc" ]]
			} );	
	  	});
		</script>
		<!-- /Datatables -->
	</body>
</html>