		<!-- Top Info Bar -->
		<div class='panel panel-default'>  
			<div class='panel-body'>
				<div class='row tile_count'>
					<div class='col-md-6 col-sm-12 col-xs-12 tile_stats_count'>
						<span class='count_top'><i class='fas fa-exchange-alt'></i> ScalarisDX servicenode trades stats</span>
						<div class='count'><?= $content['nodeCount'] ?> <small>Servicenodes facilitated at least 1 trade</small></div>
						<span class='count_bottom'><?= $content['period'] ?></span>
					</div>
					<div class='col-md-3 col-sm-6 col-xs-6 tile_stats_count'>
						<span class='count_top'><i class='fas fa-exchange-alt'></i> Total trades </span>
						<div class='count'><?= $content['totalTrades'] ?> <small> this period</small></div>
						<span class='count_bottom'><?= $content['period'] ?></span>
					</div>
					<div class='col-md-3 col-sm-6 col-xs-6 tile_stats_count'>
						<span class='count_top'><i class='fas fa-exchange-alt'></i> Total fees</span>
						<div class='count'><?= $content['totalFees'] ?> <small> SCA</small></div>
						<span class='count_bottom'><?= $content['period'] ?></span>
					</div>
				</div>
			</div>
		</div>
		<!-- Top Info Bar End-->
		<div class='clearfix'></div>
		<div class='row'>
			<div class='col-md-3 col-sm-3 col-xs-12'>
				<?php if(!empty($error)){ ?> <div class='alert alert-danger' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
				<?= $error ?> </div><?php }
				if(!empty($message)){ ?> <div class='alert alert-success' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
				<?= $message ?> </div><?php } ?>
			</div>  
		</div>

		<!-- Content -->				   
		<div class='row'>
			<!-- Open orders list -->
			<div class='col-md-12 col-sm-12 col-xs-12'>
				<div class='x_panel'>
					<div class='x_title'>
						<h2>Completed trades statistics<small> </small></h2>
						<div class='clearfix'></div>
					</div>
					<div class='x_content'>
						<table id='orders' class='table table-striped table-bordered table-valign'>
							<thead>
								<tr>
							 		<th>Servicenode</th>
									<th>Trades</th>
									<th>Fees (SCA)</th>
									<th>Explore</th>
								</tr>
					  		</thead>
							<tbody>
								<?php if ($content['nodeCount'] > 0) {;
							  		foreach($content['taf'] as $row){ ?>
									<tr>
										<td><?=$row['servicenode'] ?></td>
										<td><?=$row['trades'] ?></td>
										<td><?=$row['fees'] ?></td>
										<td>										   
											<div class='btn-group pull-right' style='padding:5px 0px 3px 0px; margin-bottom:0px'>
											    <button type='button' class='btn btn-default btn-xs'>Details</button>
												<button type='button' class='btn btn-default dropdown-toggle btn-xs' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
													<span class='caret'></span>
													<span class='sr-only'>Toggle Dropdown</span>
												</button>
												<ul class='dropdown-menu'>
												    <li><a href='?p=tradesfees&days=1' target='_self'>1 day</a></li>
												    <li><a href='?p=tradesfees&days=7' target='_self'>7 days</a></li>
												    <li><a href='?p=tradesfees&days=14' target='_self'>14 days</a></li>
												    <li><a href='?p=tradesfees&days=30' target='_self'>30 days</a></li>
												    <li><a href='?p=tradesfees' target='_self'>All time</a></li>
													<li class='divider'></li>
												    <li><a href="?p=pastorders&days=<?= $content['days'] ?>&snode=<?= $row['servicenode'] ?>" target='_self'>This node trades</a></li>
													<li class='divider'></li>
													<li><a href="https://explorer.scalaris.info/address/<?= $row['servicenode'] ?>" target='_blank'><i class='fa fa-globe fa-lg' style='color:lightblue'></i> Iquidus</a></li>
												</ul>
											</div>										   
								   		</td>
									</tr>
								<?php } } ?>						
							</tbody>
						</table>
					</div>
					<div class='clearfix'></div>
				</div>
			</div>
		</div>
		<!-- /page content -->
		</div>

		<!-- footer content -->
		<?php include('views/footer.phtml') ?>
		<!-- /footer content -->
		</div>
		</div>

		<!-- jQuery -->
		<script src='assets/js/jquery.min.js'></script>
		<!-- Bootstrap -->
		<script src='assets/js/bootstrap.min.js'></script>
		<!-- Datatables -->
		<script src='assets/js/jquery.dataTables.min.js'></script>
		<script src='assets/js/dataTables.bootstrap.min.js'></script>
		<script src='assets/js/dataTables.buttons.min.js'></script>
		<script src='assets/js/responsive.bootstrap.js'></script>

		<!-- Custom Theme Scripts -->
		<script src='assets/js/custom.min.js'></script>

		<!-- Datatables -->
		<script>
	 		$(document).ready(function() {
			$('#orders').DataTable( {
				'paging': true,
				'lengthChange': true,
				'lengthMenu': [ [10, 25, 50, -1], [10, 25, 50, 'All'] ],
				'bInfo': false,
				'order': [[ 2, 'desc' ]]
			} );		
	  		});
		</script>
		<!-- /Datatables -->
  	</body>
</html>